[project]
name = "movies-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp",
    "pandas>=2.3.1",
    "tqdm>=4.67.1",
]
